// Next Imports
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

// React Imports
import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

// Styles
import styles from '../styles/Home.module.css'
import mdStyles from '../styles/github-markdown.module.css'

// Chakra UI Imports
import {
    Box, CircularProgress, useColorModeValue, Text, Tooltip, Tag, HStack,
    useToast
} from '@chakra-ui/react'

// Msal Imports
import { AuthenticatedTemplate, UnauthenticatedTemplate } from "@azure/msal-react";

// Module Imports
//import { gql_functions as func } from "../utils/gql"
import { rest_functions as func } from "../utils/rest"
import { human_time_diff } from "../utils/misc"
import Footer from "../components/footer"


export default function Home({ user, setUser, accessToken, cacheChecked }) {
    const [articles, setArticles] = useState([]);
    const [isFetched, setIsFetched] = useState(false);

    // Utility function for (re)fetching articles
    const fetch_articles = async () => {
        func.get_all_articles(accessToken, true).then(data => {
            if (data != null && data != undefined) {
                setArticles(data);
            } else {
                setArticles([]);
                // let the loader know to stop on edge case of no data
                setIsFetched(true);
            }
        }).catch(err => {
            console.log(err);
            setIsFetched(true);
        });
    }

    // Initial data fetching (wait for cache to be checked)
    useEffect(() => {
        if (!isFetched && cacheChecked) {
            fetch_articles();
        }
    }, [cacheChecked])

    // Remove loading animation on data being fetched
    useEffect(() => {
        if (cacheChecked) {
            setIsFetched(true);
        }
    }, [articles])

    const basecolor = useColorModeValue('whitesmoke', 'gray.800');
    const bgcolor = useColorModeValue('white', 'gray.800');

  return (
      <Box bg={basecolor} className={styles.container}>

          <Head>
              <title>Hawaii-CMS</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
              <Box bg={bgcolor} className={styles.header} boxShadow="md">
                  <h1 className={styles.title}>
                      Welcome to Hawaii-CMS!
                  </h1>

                  <p className={styles.description}>
                      Made with <a href="https://nextjs.org">Next.js</a>, MS SQL, and Azure Data API Builder
                  </p>
              </Box>
              <Box p={10}/>
              <div className={styles.grid}>
                  {!isFetched &&
                      <div className={styles.loader}>
                          <CircularProgress isIndeterminate color='green.300' />
                      </div>}
                      {articles.slice(0).reverse().map((article) => (
                          <Box key={article.id} className={styles.card} bg={bgcolor} boxShadow={'lg'}>
                              <div className={styles.post_header} style={{ backgroundColor: (user != null && user.username == article.author_email) ? "#ddf4ff" : "#edf2f7"}}>
                                  <HStack>
                                      <Tooltip label={article.author_email}> 
                                          <Text fontWeight="semibold"> {article.author_name} </Text>
                                      </Tooltip>
                                      <Text> published {human_time_diff(article.published)} ago </Text>
                                  </HStack>
                                  <Tooltip label={new Date(`${article.published}Z`).toLocaleTimeString()}>
                                      <Text> {new Date(`${article.published}Z`).toLocaleDateString()} </Text>
                                  </Tooltip>
                            </div>
                            
                            <div className={mdStyles["markdown-body"]} style={{ padding: "1.5em", borderRadius: "0px 0px 10px 10px" }} >
                                <h1 style={{ fontSize: "2.5em"}}> {article.title} </h1>
                                <ReactMarkdown className={mdStyles["markdown-body"]} remarkPlugins={[remarkGfm]} >
                                    {article.body}
                                </ReactMarkdown>
                            </div>
                        </Box>

                    ))}
              </div>

          </main>
          <Footer/>
      </Box>
  )
}
